apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinebook
  template:
    metadata:
      labels:
        app: cinebook
    spec:
      containers:
        - name: cinebook
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000 
